import type { ProductWithVariants } from "@/lib/types";

export const DEMO_PRODUCTS: ProductWithVariants[] = [
  {
    id: "demo-1",
    name: "Charizard ex",
    slug: "charizard-ex-151",
    description: "Scarlet & Violet—151 特別插畫稀有",
    type: "SINGLE",
    cardSet: "Scarlet & Violet—151",
    cardNumber: "199/165",
    rarity: "Special Illustration Rare",
    pokemonType: "Fire",
    language: "zh-HK",
    images: [
      {
        id: "img-1",
        url: "https://images.pokemontcg.io/sv3pt5/199_hires.png",
        alt: "Charizard ex",
      },
    ],
    variants: [
      {
        id: "var-1-nm",
        condition: "Near Mint (NM)",
        isFoil: false,
        price: 1280,
        stock: 3,
        sku: "SV151-199-NM",
      },
      {
        id: "var-1-lp",
        condition: "Lightly Played (LP)",
        isFoil: false,
        price: 980,
        stock: 2,
        sku: "SV151-199-LP",
      },
    ],
  },
  {
    id: "demo-2",
    name: "Mew ex",
    slug: "mew-ex-151",
    description: "Scarlet & Violet—151 超稀有",
    type: "SINGLE",
    cardSet: "Scarlet & Violet—151",
    cardNumber: "193/165",
    rarity: "Ultra Rare",
    pokemonType: "Psychic",
    language: "zh-HK",
    images: [
      {
        id: "img-2",
        url: "https://images.pokemontcg.io/sv3pt5/193_hires.png",
        alt: "Mew ex",
      },
    ],
    variants: [
      {
        id: "var-2-nm",
        condition: "Near Mint (NM)",
        isFoil: false,
        price: 180,
        stock: 12,
        sku: "SV151-193-NM",
      },
    ],
  },
  {
    id: "demo-3",
    name: "Pikachu",
    slug: "pikachu-151",
    description: "Scarlet & Violet—151 普通卡",
    type: "SINGLE",
    cardSet: "Scarlet & Violet—151",
    cardNumber: "025/165",
    rarity: "Common",
    pokemonType: "Lightning",
    language: "zh-HK",
    images: [
      {
        id: "img-3",
        url: "https://images.pokemontcg.io/sv3pt5/25_hires.png",
        alt: "Pikachu",
      },
    ],
    variants: [
      {
        id: "var-3-nm",
        condition: "Near Mint (NM)",
        isFoil: false,
        price: 15,
        stock: 50,
        sku: "SV151-025-NM",
      },
      {
        id: "var-3-foil",
        condition: "Near Mint (NM)",
        isFoil: true,
        price: 45,
        stock: 20,
        sku: "SV151-025-FOIL",
      },
    ],
  },
  {
    id: "demo-4",
    name: "Scarlet & Violet—151 補充包",
    slug: "sv151-booster",
    description: "繁體中文版補充包，每包 10 張",
    type: "BOOSTER_PACK",
    cardSet: "Scarlet & Violet—151",
    cardNumber: null,
    rarity: null,
    pokemonType: null,
    language: "zh-HK",
    images: [
      {
        id: "img-4",
        url: "https://images.pokemontcg.io/sv3pt5/logo.png",
        alt: "SV151 Booster",
      },
    ],
    variants: [
      {
        id: "var-4-sealed",
        condition: "Sealed",
        isFoil: false,
        price: 55,
        stock: 200,
        sku: "SV151-BOOSTER",
      },
    ],
  },
  {
    id: "demo-5",
    name: "Scarlet & Violet—151 精英訓練家禮盒",
    slug: "sv151-etb",
    description: "ETB 封盒，含 9 包補充包及配件",
    type: "SEALED_BOX",
    cardSet: "Scarlet & Violet—151",
    cardNumber: null,
    rarity: null,
    pokemonType: null,
    language: "zh-HK",
    images: [
      {
        id: "img-5",
        url: "https://images.pokemontcg.io/sv3pt5/logo.png",
        alt: "SV151 ETB",
      },
    ],
    variants: [
      {
        id: "var-5-sealed",
        condition: "Sealed",
        isFoil: false,
        price: 480,
        stock: 15,
        sku: "SV151-ETB",
      },
    ],
  },
  {
    id: "demo-6",
    name: "Umbreon VMAX",
    slug: "umbreon-vmax-evolving",
    description: "Evolving Skies 月亮伊布 VMAX",
    type: "SINGLE",
    cardSet: "Evolving Skies",
    cardNumber: "215/203",
    rarity: "Secret Rare",
    pokemonType: "Darkness",
    language: "en",
    images: [
      {
        id: "img-6",
        url: "https://images.pokemontcg.io/swsh7/215_hires.png",
        alt: "Umbreon VMAX",
      },
    ],
    variants: [
      {
        id: "var-6-nm",
        condition: "Near Mint (NM)",
        isFoil: false,
        price: 3200,
        stock: 1,
        sku: "EVS-215-NM",
      },
    ],
  },
];

export const DEMO_TOURNAMENTS = [
  {
    id: "t-1",
    title: "週六標準賽 #12",
    slug: "standard-sat-12",
    description: "Pokémon TCG 標準賽制，瑞士輪 + 淘汰賽",
    format: "Standard",
    maxPlayers: 32,
    entryFee: 80,
    prizePool: "優勝：補充包 x6 + 店舖點數",
    location: "旺角店",
    startsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    registrationDeadline: new Date(
      Date.now() + 2 * 24 * 60 * 60 * 1000,
    ).toISOString(),
    durationMinutes: 180,
    status: "OPEN",
    registeredCount: 18,
  },
  {
    id: "t-2",
    title: "新手友善賽",
    slug: "beginner-friendly",
    description: "適合初學者，現場有教學員指導",
    format: "Standard",
    maxPlayers: 16,
    entryFee: 50,
    prizePool: "參加即送卡套",
    location: "銅鑼灣店",
    startsAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    registrationDeadline: new Date(
      Date.now() + 6 * 24 * 60 * 60 * 1000,
    ).toISOString(),
    durationMinutes: 120,
    status: "OPEN",
    registeredCount: 8,
  },
];
