-- Migration: Denormalize StockRecord to survive product/variant deletion
-- Changes: variantId nullable, onDelete SetNull, add denormalized display fields

-- 1. Add denormalized columns (nullable first for backfill)
ALTER TABLE "StockRecord"
  ADD COLUMN "productName" TEXT,
  ADD COLUMN "variantCondition" TEXT,
  ADD COLUMN "variantIsFoil" BOOLEAN NOT NULL DEFAULT false;

-- 2. Backfill denormalized data from existing variant + product
UPDATE "StockRecord" sr
SET
  "productName" = p."name",
  "variantCondition" = pv."condition",
  "variantIsFoil" = pv."isFoil"
FROM "ProductVariant" pv
JOIN "Product" p ON p."id" = pv."productId"
WHERE sr."variantId" = pv."id";

-- 3. Set NOT NULL on productName and variantCondition after backfill
ALTER TABLE "StockRecord"
  ALTER COLUMN "productName" SET NOT NULL,
  ALTER COLUMN "variantCondition" SET NOT NULL;

-- 4. Drop the existing FK constraint (onDelete: Cascade) and recreate as SetNull
-- The constraint name is auto-generated by Prisma: StockRecord_variantId_fkey
ALTER TABLE "StockRecord"
  DROP CONSTRAINT IF EXISTS "StockRecord_variantId_fkey";

ALTER TABLE "StockRecord"
  ADD CONSTRAINT "StockRecord_variantId_fkey"
  FOREIGN KEY ("variantId") REFERENCES "ProductVariant"("id")
  ON DELETE SET NULL;

-- 5. Make variantId nullable
ALTER TABLE "StockRecord"
  ALTER COLUMN "variantId" DROP NOT NULL;
